In [ ]:
'''Q1. What is a database? Differentiate between SQL and NoSQL databases.

Ans - A database is an organized collection of structured information, or data, typically stored electronically in a computer system.
     Difference between SQL and NoSQL databases are as follows:

     1. SQL is a realtional database which onlt deals with rows and columns on the other hand NoSQL is a non-relational database, meaning it allows 
     different structures than a SQL database (not rows and columns) and more flexibility to use a format that best fits the data.
     
     2. Working-
            SQL databases are valuable in handling structured data, or data that has relationships between its variables and entities where NoSQL systems 
            allow you to work with different data structures within a database. Because they allow a dynamic schema for unstructured data, ther's less need 
            to pre-plan and pre-organize data, and it's easier to make modifications. NoSQL databases allow you to add new attributes and fields, as well as 
            use varied syntax across databases.

     3. Scalability-
            In general, SQL databases can scale vertically, meaning you can increase the load on a server by migrating to a larger server that adds more CPU, 
            RAM or SSD capability. While vertical scalability is used most frequently, SQL databases can also scale horizontally through sharding or 
            partitioning logic, although that's not well-supported where NoSQL databases scale better horizontally, which means one can add additional servers 
            or nodes as needed to increase load.

     4. Structure- 
           SQL database schema organizes data in relational, tabular ways, using tables with columns or attributes and rows of records. Because SQL works with
           such a strictly predefined schema, it requires organizing and structuring data before starting with the SQL database.
           NoSQL databases are not relational, so they don’t solely store data in rows and tables. Instead, they generally fall into one of four types of 
           structures:
              (a) Column-oriented, where data is stored in cells grouped in a virtually unlimited number of columns rather than rows.
              (b) Key-value stores, which use an associative array (also known as a dictionary or map) as their data model. This model represents data as a 
              collection of key-value pairs.
              (c) Document stores, which use documents to hold and encode data in standard formats, including XML, YAML, JSON (JavaScript Object Notation) 
              and BSON. A benefit is that documents within a single database can have different data types.
              (d) Graph databases, which represent data on a graph that shows how different sets of data relate to each other. Neo4j, RedisGraph (a graph 
              module built into Redis) and OrientDB are examples of graph databases.

     5. Properties- RDBMS, which use SQL, must exhibit four properties, known by the acronym ACID. These ensure that transactions are processed successfully 
              and that the SQL database has a high level of reliability:
              (a) Atomicity: All transactions must succeed or fail completely and cannot be left partially complete, even in the case of system failure.
              (b) Consistency: The database must follow rules that validate and prevent corruption at every step.
              (c) Isolation: Concurrent transactions cannot affect each other.
              (d) Durability: Transactions are final, and even system failure cannot “roll back” a complete transaction.
       
              While SQL calls for ACID properties, NoSQL follows the CAP theory (although some NoSQL databases — such as IBM's DB2, MongoDB, AWS's DynamoDB 
              and Apache's CouchDB — can also integrate and follow ACID rules).
              The CAP theorem says that distributed data systems allow a trade-off that can guarantee only two of the following three properties (which form 
              the acronym CAP) at any one time:
              (a) Consistency: Every request receives either the most recent result or an error. MongoDB is an example of a strongly consistent system, 
                  whereas others such as Cassandra offer eventual consistency.
              (b) Availability: Every request has a non-error result.
              (c) Partition tolerance: Any delays or losses between nodes do not interrupt the system operation.

       6. Support-
               Because SQL databases have a long history now, they have huge communities, and many examples of their stable codebases online. There are many 
               experts available to support SQL and programming relational data.
               While NoSQL has quickly been adopted, it has smaller user communities and, therefore, less support. NoSQL users do benefit from open-source 
               systems, as opposed to the many SQL languages that are proprietary.

       7. Examples-
              SQL databases - Db2, MySQL, PostgreSQL, YugabyteDB, CockroachDB, Oracle Database, Microsoft SQL Server, Azure SQL Database.
              NoSQL databases - Redis, FaunaDB, CouchDB, MongoDB, Cassandra, Elasticsearch, BigTable, Neo4j, HBase
'''

In [ ]:
'''Q2. What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example.

Ans - DDL is Data Definition Language.

    CREATE - creating tables and columns.
    e.g. CREATE TABLE table_name(column1 datatype, column2 datatype, column3 datatype);
    Datatype can be VARCHAR, CHAR, INT, FLOAT etc.

    DROP - deleting entire table at once.
    e.g. DROP TABLE table_name;


    ALTER - altering tables, add and drop columns.
    e.g. ALTER TABLE table_name ADD COLUMN column_name datatype; #for adding column to table
         ALTER TABLE table_name ALTER COLUMN column_name SET DATATYPE datatype; #for altering column properties within table
        ALTER TABLE table_name DROP COLUMN column_name ; #for deleting column within the table

    TRUNCATE - delets all rows witin the table but not the table and operation can't be undone.
    e.g. TRUNCATE TABLE table_name IMMEDIATE;
'''

In [ ]:
''' Q3. What is DML? Explain INSERT, UPDATE, and DELETE with an example.

Ans - DML is Data Manupulation Language.

    INSERT - To populate the created table, to add new rows to table.
    e.g. INSERT INTO TABLE table_name, (column1 , column2 , column3 ), (value1 , value2 , value3 );

    UPDATE - To read and modify data.
    e.g. UPDATE table_name
         SET (column_name) = (value)
         WHERE (condition);


    DELETE - To delete one or more rows from the table.
    e.g. DELETE table_name WHERE condition;
        

'''

In [ ]:
''' Q4. What is DQL? Explain SELECT with an example.

Ans - DQL is Data Query Language.

    SELECT- to extract data from a database.
    e.g. SELECT column FROM table_name WHERE conditions;

'''

In [ ]:
''' Q5. Explain Primary Key and Foreign Key.

Ans- Primary Key: 
        A primary key is used to ensure that data in the specific column is unique. 
        A column cannot have NULL values. 
        It is either an existing table column or a column that is specifically generated by the database according to a defined sequence. 

    Foreign Key: 
        A foreign key is a column or group of columns in a relational database table that provides a link between data in two tables. 
        It is a column (or columns) that references a column (most often the primary key) of another table. 

    Difference between Primary Key and Foreign Key:

S.NO.                               PRIMARY KEY	                                                             FOREIGN KEY

  1	     A primary key is used to ensure data in the specific column is unique.	   A foreign key is a column or group of columns in a relational database 
                                                                                       table that provides a link between data in two tables.

  2	     It uniquely identifies a record in the relational database table.	       It refers to the field in a table which is the primary key of another 
                                                                                        table.

  3	     Only one primary key is allowed in a table.	                           Whereas more than one foreign key are allowed in a table.

  4	     It is a combination of UNIQUE and Not Null constraints.	               It can contain duplicate values and a table in a relational database.

  5	     It does not allow NULL values.	                                           It can also contain NULL values.

  6	     Its value cannot be deleted from the parent table.	                       Its value can be deleted from the child table.

  7	     It constraint can be implicitly defined on the temporary tables.	       It constraint cannot be defined on the local or global temporary tables.
'''

In [ ]:
'''Q6. Write a python code to connect MySQL to python. Explain the cursor() and execute() method.

Ans - Following is the python code to connect MySQL to python
            
            import mysql.connector
            mydb = mysql.connector.connect(
                host="localhost",
                user="abc",
                password="password"
                )
            print(mydb)

            mycursor = mydb.cursor()
            mycursor.execute("SHOW DATABASES")
            for x in mycursor:
            print(x)

The cursor method in database is a construct which allows you to iterate/traversal the records of a table.

The Execute method executes a specified query, SQL statement, stored procedure, or provider-specific text.
'''

In [ ]:
''' Q7. Give the order of execution of SQL clauses in an SQL query.

ANS-  In SQL, the first clause that is processed is the FROM clause, while the SELECT clause, which appears first in 
    an SQL query, is processed much later. The phases involved in the logical processing of an SQL query are as 
    follows:

        FROM clause
        ON clause
        OUTER clause
        WHERE clause
        GROUP BY clause
        HAVING clause
        SELECT clause
        DISTINCT clause
        ORDER BY clause
        TOP clause

'''